<?php
	echo '
	<div class="contact">
<p><strong>
ABOUT 
<br>
<br>
Nationally and internationally recognised photographer Christina Simons has worked in the film &amp; photography industry for over fifteen years.  
<br>
<br>

Partly Icelandic, partly American, Christina\'s unusual heritage &amp; anthropological interest drives her exploration of the truth in issues, cultures &amp; places, leading to exhibitions throughout Australia. Her interests range from lifestyle &amp; food, portraiture, travel, and documentary photography. Her work has featured in The New York Times and The Times in the UK, along with various local publications whilst a regular contributor of stories to the The Big Issue. 

<br>
<br>
Christina is currently based in Melbourne Australia, however when not on assignment she likes to spend part of the year in Iceland. She can be reached no matter what corner of the globe on the below email address and phone number. Her social media pages are also a good means of contact and keeping up to date with what she\'s up to and where.
<br>
<br>
------------------------------------------------------------------------------------------------------
<br>
<br>
EXHIBITIONS 
<br>
<br>
<em>Roller Derby - <a title="CCP Documentary Photography Awards" href="http://www.ccp.org.au/exhibitions.php?f=20111211_Gallery_1" target="_blank">Finalist in the CCP Documentary Photography Awards</a>.</em>
Centre for Contemporary Photography 
Fitzroy, Melbourne, Victoria. Nov 2011. 
<br>
<br>
<em>Roller Derby. </em>
Australia Wide Tour. 2012-2013.</em>
<br>
<br>
<em> Human Landscape.</em>
 Salus Spa, Daylesford, Victoria. 2010.
<br>
<br>
<em> The Haiti Project.</em> 
Uber Gallery, St Kilda, Melbourne, Victoria. February 2007.
 
Storm Gallery, Surry Hills, Sydney, NSW. April 2010.
 The Albury Library Museum, Albury, NSW. February – April, 2011.
<br>
<br>
 Collaborative Projects with artist Jill Orr.
<em> <a title="Vision" href="http://www.jennyportgallery.com.au/exhibitions/vision.html" target="_blank">Vision</a></em>.
 Jenny Port Gallery, Melbourne, June 2010.
<em> <a title="Between Somewhere and Nowhere" href="http://www.jennyportgallery.com.au/exhibitions/2011_jorr_between.html" target="_blank">Between Somewhere and Nowhere</a></em>.
 Jenny Port Gallery, Melbourne, Nov 2011.
<a title="The Promised Land." href="http://www.jennyportgallery.com.au/exhibitions/2012_jorr_promisedland.html" target="_blank"><em>The Promised Land.</em></a>
<em></em>John Buckley Gallery, Melbourne, 2012.
<br>
<br>
------------------------------------------------------------------------------------------------------
<br>
<br>
CONTACT
<br>
<br>
agent | <a title="Polaris Images New York" href="http://www.polarisimages.com" target="_blank">Polaris Images</a> for assignments worldwide
<br>
email | christina@christinasimons.com.au
<br>
mobile | +61 (0)405 271 011
<br>
<br>
<br>
<a href="http://au.linkedin.com/in/christinasimons" class="pageLink">LinkedIn</a>
<br>
<iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2F%23%21%2Fpages%2FMoksha-Productions-Photography-by-Christina-Simons%2F107976072580412&amp;layout=standard&amp;show_faces=false&amp;width=250&amp;action=like&amp;font=arial&amp;colorscheme=light&amp;height=40" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:250px; height:40px;" allowTransparency="true"></iframe>
<br>

<a href="http://twitter.com/share" class="twitter-share-button" data-url="http://www.christinasimons.com" data-text="See more photos from Moksha at:" data-count="none" data-via="MokshaProd">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
<br>
<br>
<br>
<br>
</strong></p>
</div>';
?>