<?php
	echo '
	<div class="contact">
	<p>
<strong>Nationally and internationally recognised photographer Christina Simons has worked in the film &amp; photography industry for over fifteen years.  </strong>
<p>
<p>
<strong>Partly Icelandic, partly American, Christina\'s unusual heritage &amp; anthropological interest drives her exploration of the truth in issues, cultures &amp; places, leading to exhibitions throughout Australia. Her interests range from lifestyle &amp; food, portraiture, travel, and documentary photography. Her work has featured in the The New York Times and The Times in the UK, along with various local publications whilst a regular contributor of stories to the The Big Issue. 
</strong>
<p>
<p>
<strong>Christina is currently based in Melbourne Australia, however when not on assignment she likes to spend part of the year in Iceland. She can be reached no matter what corner of the globe on the below email address and phone number. Her social media pages are also a good means of contact and keeping up to date with what she\'s up to and where.</strong>
<p>
<strong>------------------------------------------------------------------------------------------------------</strong>
<p>
<strong>Christina has exhibited in several solo exhibitions as well as collaboratively. </strong>
<p>
<p>
<strong>Roller Derby - <a title="CCP Documentary Photography Awards" href="http://www.ccp.org.au/exhibitions.php?f=20111211_Gallery_1" target="_blank">Finalist in the CCP Documentary Photography Awards</a>.</strong></em>
<strong>Centre for Contemporary Photography </strong>
<strong>Fitzroy, Melbourne, Victoria. Nov 2011. </strong>
<p>
<em><strong>Roller Derby </strong>
<strong>Australia Wide Tour. 2012-2013.</strong></em>
<p>
<em><strong> Human Landscape.</strong></em>
<strong> Salus Spa, Daylesford, Victoria. 2010.</strong>
<p>
<p>
<em><strong> The Haiti Project.</strong></em>
<strong> 
Uber Gallery, St Kilda, Melbourne, Victoria. February 2007.</strong>
<strong> 
Storm Gallery, Surry Hills, Sydney, NSW. April 2010.</strong>
<strong> The Albury Library Museum, Albury, NSW. February – April, 2011.</strong>
<p>
<p>
<strong> Collaborative Projects with artist Jill Orr:</strong>
<strong><em> <a title="Vision" href="http://www.jennyportgallery.com.au/exhibitions/vision.html" target="_blank">Vision</a></em>.</strong>
<strong> Jenny Port Gallery, Richmond, Melbourne, Victoria. June 2010.</strong>
<strong><em> <a title="Between Somewhere and Nowhere" href="http://www.jennyportgallery.com.au/exhibitions/2011_jorr_between.html" target="_blank">Between Somewhere and Nowhere</a></em>.</strong>
<strong> Jenny Port Gallery, Richmond, Melbourne, Victoria.  Nov 2011.</strong>
<a title="The Promised Land." href="http://www.jennyportgallery.com.au/exhibitions/2012_jorr_promisedland.html" target="_blank"><strong><em>The Promised Land.</em></strong></a>
<strong><em></em>Jenny Port Gallery hosted by the John Buckley Gallery, Melbourne, 2012.</strong>
<p>
<p>
<p>
<p>
christina@christinasimons.com.au
<p>
+61 (0)405 271 011
<p>
<p>
Christina is represented by Polaris in New York for assignments in and around Australasia and worldwide: <a href="http://www.polarisimages.com">www.polarisimages.com</a>
<p>
<p>
<a href="http://au.linkedin.com/in/christinasimons" class="pageLink">Connect with me on LinkedIn</a>
<p>
<iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2F%23%21%2Fpages%2FMoksha-Productions-Photography-by-Christina-Simons%2F107976072580412&amp;layout=standard&amp;show_faces=false&amp;width=250&amp;action=like&amp;font=arial&amp;colorscheme=light&amp;height=40" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:250px; height:40px;" allowTransparency="true"></iframe>
<p>
<a href="http://twitter.com/share" class="twitter-share-button" data-url="http://www.christinasimons.com" data-text="See more photos from Moksha at:" data-count="none" data-via="MokshaProd">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
</p>
</div>';
?>