<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><!-- InstanceBegin template="/Templates/commercial_home.dwt" codeOutsideHTMLIsLocked="false" -->
	<head>
		<title><?php echo $pageTitle; ?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<link href="css/moksha.css" rel="stylesheet" type="text/css" />
		<script type="text/javascript">
			<!--
				var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
				document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
			-->
		</script>

		<script type="text/javascript">
			<!--
				try
				{
					var pageTracker = _gat._getTracker("UA-11028043-1");
					pageTracker._trackPageview();
				}
				catch(err) {}
			-->
		</script>
	</head>

	<body id="<?php echo $sectionColour; ?>">
	<div id="frame">